### PR TITLE
Updated readme file for correlation examples

### PR DESCRIPTION
**Pull request by kafischer**
Updated readme file to point to new examples for two-time correlations with time-dependent Liouvillians

### CODE REVIEW

**Comment by ajgpitch** [comment]
Looks fine to me. 
Will merge if there are no objections

**Comment by kafischer** [comment]
Hi Alex, Could you please merge this change and with the PR#25 in the notebooks repository?

Thanks!

**Comment by ajgpitch** [comment]
Sorry for delay

**Comment by ajgpitch** [comment]
btw did you see my google groups message about Zenodo ref (specifically updating your GitHub full name)?

**Comment by kafischer** [comment]
I missed it thanks for the heads up!

**Pull request merged**
