### PR TITLE
Update qobjevo.ipynb

### PR DESCRIPTION
**Pull request by jakelishman**
Update to be a little clearer, and hopefully provide some explanations as to why these different components might be useful.

@nathanshammah: as requested by you in the last meeting.

### CODE REVIEW

**Comment by jakelishman** [comment]
Sounds good.  Also at some point we should add a similar section to the User Guide in the full docs.

As for adding my name: I'm not a big fan to be honest - these things then just tend to end up with 8 names on them after a year, which kind of just makes a mess. Surely it's just owned by QuTiP as an organisation, and there's the possibility of credit for major contributions to the underlying code?

**Comment by nathanshammah** [comment]
Yes, if you have time that's also something that can be added. Big chunks of the notebook can go in the docs. 

QuTiP notebooks are not touched much after addition. They are one or at most a couple of authors. It is mainly there (possibly with email) as a reference for interested users, including those not so familiar with Github, and GH History, but going on the website.

**Comment by jakelishman** [comment]
I forgot about this.

All done, except for the "from beginning to end" example.  There's a reasonable chance that the usage may change a bit for the upcoming QuTiP 5, and I'd rather get that finalised (and write all the documentation for the new data layer) before I start spending a lot of time sorting out missing documentation here.

The PR for qutip.org is qutip/qutip.github.io#119.

**Comment by jakelishman** [comment]
That's a bit worrying about the internal links - I really don't know much about Jupyter at all because I don't use it, but it did work locally on my machine.

**Pull request merged**
