### PR TITLE
Piqs Notebooks

### PR DESCRIPTION
**Pull request by nathanshammah**
@ajgpitch Dear Alex, these are the updated notebooks, they run in the merged version of Piqs. The three notebooks are renamed as "piqs_...". I will add more notebooks once we upload the manuscript on the arXiv.

### CODE REVIEW

**Comment by nathanshammah** [comment]
Regarding the last change: Improved readability of markup of equations that now render also on GitHub. Changed definition of g2(tau). Added/changed text.

**Comment by ajgpitch** [comment]
@nathanshammah I tried running `piqs_introduction` against the latest qutip/master

I got this error when running `In[15]:`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-2c02a29de33b> in <module>()
     10 rho7 = np.real(ground_state.full())
     11 rho8 = np.real(subradiant_state.full())
---> 12 rho9 = np.real(dicke_basis.todense())

AttributeError: 'numpy.ndarray' object has no attribute 'todense'
```
Seems like it should be an easy fix

**Comment by ajgpitch** [comment]
The notebook is looking generally great btw. Really good work

**Comment by nathanshammah** [comment]
Dear Alex, thank you. For some reason I was not getting that error. I changed the name of that variable, as it is also the name of a function and that might give the error. I also enhanced the notebook in several parts. In particular the last subplots now are more compact.

**Comment by ajgpitch** [comment]
I's still getting the error. I think when you do `dicke_blocks = np.real(block_matrix(N))` then `np.real` converts to a dense matrix, hence `dicke_blocks.todense()` errors.
Maybe it's a numpy version thing. This is my version info
```
QuTiP Version:      4.3.0.dev0+cdc2204
Numpy Version:      1.12.0
Scipy Version:      0.19.0
Cython Version:     0.25.2
Matplotlib Version: 2.0.0
Python Version:     3.6.0
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)
```

I changed to:
```
dicke_blocks = np.real(block_matrix(N).todense())
```
...
```
rho9 = dicke_blocks
```
and it works fine

**Comment by ajgpitch** [comment]
Also the final box needs
```
plt.show()
plt.close()
```
otherwise no plots

**Comment by nathanshammah** [comment]
Dear @ajgpitch, I hope now it works fine. My Numpy version is 1.13.3, Scipy 1.0, Matplotlib 2.1.1. Thank you.

> QuTiP Version:      4.3.0.dev0+cdc2204a
> Numpy Version:      1.13.3
> Scipy Version:      1.0.0
> Cython Version:     0.27.3
> Matplotlib Version: 2.1.1
> Python Version:     3.6.3
> Number of CPUs:     2
> BLAS Info:          INTEL MKL
> OPENMP Installed:   False
> INTEL MKL Ext:      True
> Platform Info:      Darwin (x86_64)

**Comment by ajgpitch** [comment]
I have checked all three notebooks. They all work fine and look pretty much ready. Just a few minor points:

In the ...intro...
This looks like a mistake (In[20])
```
rho9 = rho9 = dicke_blocks
```

In ...steadystate...
You need to run the `qutip.about()` box.
Wouldn't normally quibble, but we have to be clear that qutip v4.3 is needed.

**Comment by nathanshammah** [comment]
Dear Alex, sorry about that. Thanks a lot.

2018-03-20 1:18 GMT+09:00 Alexander Pitchford <notifications@github.com>:

**Comment by ajgpitch** [comment]
Thanks again for these model notebooks

**Pull request merged**
