### PR TITLE
Example notebook for rcsolver

### PR DESCRIPTION
**Pull request by anubhavvardhan**

### CODE REVIEW

**Comment by anubhavvardhan** [comment]
@nonhermitian , @jrjohansson ....this good enough?

**Comment by nonhermitian** [comment]
- Using dots instead of multiplication signs is confusing as those are also used to access methods of objects and what not.

- I do not understand why there are two plots P1 and P12 for the same quantity.

- And the section on the Wigner function just plots the same Photon number distribution.

**Comment by anubhavvardhan** [comment]
@nonhermitian ...need some help with the options part.....store_states is True but output.states is being shown as an empty list after the new version of the code as implemented

**Comment by anubhavvardhan** [comment]
Everything works now.

**Comment by nonhermitian** [comment]
Merging this now.  Thanks.

**Pull request merged**
