### PR TITLE
Import the BoFiN example notebooks.

### PR DESCRIPTION
**Pull request by hodgestar**
*Description*

Import the example notebooks from https://github.com/tehruhn/bofin.

*Todo*

- [x] Merge HEOM into QuTiP (https://github.com/qutip/qutip/pull/1601)
- [x] Update heom-1a-spin-bath-model-basic
- [x] Update heom-1b-spin-bath-model-underdamped-sd
- [x] Update heom-1c-spin-bath-model-pure-dephasing
- [x] Update heom-1d-spin-bath-model-ohmic-fitting
- [x] Update heom-1e-spin-bath-model-very-strong-coupling
- [x] Update heom-2-fmo-example
- [x] Add heom-3-quantum-heat-transport
- [x] Update heom-4-dynamical-decoupling
- [x] Update heom-5a-fermions-discrete-boson-model
- [x] Update heom-5b-fermions-single-impurity-model
- [x] Add an index notebook with links to the other notebooks and a sentence about each
- [x] Reorder and rename examples 1 to match the other in the paper: a, e, b, d (and c is not in the paper so it should go at the end)
- [x] Go through 1d (the fitting example) and fix bugs, decide on plots to keep from the end, and deal with a few notes.
- [x] Add arxiv link to BoFiN paper so the people can see where the figures end up
- [x] Once everything else is done, do a final pass through the notebooks
- [x] Uncomment and clean up figure saving

*Notes:*

* I'm also experimenting with jupytext md:myst versions of the notebooks to make reviewing changes easier. See, e.g., af6186d.
* To automatically save the notebooks to both markdown and .ipynb, just `pip install jupytext` (or similar) and restart your notebook server.
* And I'm planning to experiment with the nbmake pytest plugin for running the notebooks (so that eventually we can run the notebooks in CI).

*Changelog*
Add example notebooks for the QuTiP 4.7 HEOM solver (based on the original BoFiN example notebooks).

### CODE REVIEW

**Comment by nwlambert** [comment]
Ah, just a ntoe, I need to push some changes to the ones in tehrun's repo, just still working through the dynamical decoupling one.  I will try and do that wednesday or thursday next week

**Comment by hodgestar** [comment]
> ..., just still working through the dynamical decoupling one. I will try and do that wednesday or thursday next week

I will leave that one for now then.

**Comment by nwlambert** [comment]
OK, I added the small changes to the other ones into the open PR on Tarun's repo.

**Comment by hodgestar** [comment]
> OK, I added the small changes to the other ones into the open PR on Tarun's repo. Mostly it was just tidying up a little, and adding some more explanatory text here and there, hopefully easy to combo with what you are doing here.

Thanks! I've merged those into this branch. It was all fine except merging `heom-1a-...`. That was a bit of a pain.

Shall we work in this branch from now on? Happy for you to make commits here if needed.

**Comment by nwlambert** [comment]
Thanks! Sorry, I should have pushed those ages ago. Yeah lets work from here from now on!

**Comment by hodgestar** [comment]
I've finished cleaning up 1d for the most part and added the index and re-ordered all the notebooks for the paper.

@nwlambert Could I ask you to tackle "Go through 1d (the fitting example) and fix bugs, decide on plots to keep from the end, and deal with a few notes"? I'm happy to go through it with you if you like, I just don't have all the information I need about what to keep and what some of the plots should look like.

**Comment by nwlambert** [comment]
Done.  Thanks for the edits, it  is a lot more readable and usable than before!

**Comment by hodgestar** [comment]
@nwlambert Yay! Do we want to go through the notebooks one last time, or are we happy with them as they are now?

**Review by nwlambert — APPROVED** [review]
Good to go from my side.

**Pull request merged**
