### PR TITLE
Notebooks for GSoC noisy device simulator

### PR DESCRIPTION
**Pull request by BoxiLi**
This PR contains 5 modified notebooks:
1. quantum-gate: Adding the Molmer-Sorensen gate and qrot gate, as well as an example of user-defined gate
2. qip-NISQ: A new notebook demonstrating noisy QIP simulation with `CircuitProcessor`.
3. qip-optpulseprocessor: A new notebook demonstrating the subclass `OptPulseProcessor`
4. qip-spin-chain-model: Adding the numerical option and noisy simulation
5. qip-circuitprocessor-DJ-algorithm: A new notebook demonstrating the implementation of Deutsche-Josza algorithm with `CircuitProcessor`

### CODE REVIEW

**Comment by BoxiLi** [comment]
Hi Nathan, thanks for the suggestions and sorry for the delay. I updated the DJ notebook according to your suggestions. Since we replaced the name `CircuitPorcessor` with `Processor`, I also changed the name of the notebook to `# Running the Deutsch–Jozsa algorithm on the NISQ device simulator`. It's a bit lengthy since I want to emphasis that we are doing a simulation of the quantum device running this algorithm. Tell me if you have a better name.

**Comment by nathanshammah** [comment]
## 1. All notebooks
- Please add your name and possibly contact email to the top of notebooks. 

## 2. quantum-gates
- Can add the fact that now gates can be applied in any position of the circuit.  
- typo: "its the attributes"
- typo (?):  "targets qubits"--> "target qubits"
- block 13 and 14: typo in comment "controlls", controls
- block 14: qutbi --> qubit
(- This notebook is full of stuff, e.g., the list of gates, but someone might miss some important information as how to play with circuit properties, given later on. I am thinking of adding a table of contents with internal links to cells. It could be nice to have the latex version of gates for all of them. I will look into these enhancements myself.)

## ## qip-NISQ
Excellent tutorial. 
Comments:
- Please consider adding a markdown paragraph at the beginning with the explicit writing of the NISQ acronym. 
- Please consider adding also a link to Preskill's **Quantum** article, citing it in that first paragraph, and putting it in a new markdown subsection just before the software versions section or at the end, similarly to [this](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/piqs-overview.ipynb#References) and other notebooks.

**Comment by nathanshammah** [comment]
## General
- At the end or somewhere at the beginning, you can add a reference to your blog, and the fact that this notebooks where done as part of NumFOCUS, GSoC.
- Think of how to list the notebooks in the tutorials page so that their relation stands out. They could be listed under the QIP section or another section just below that or a subsection of that.
- update this PR title from GoSC to GSoC. Also in the notebooks. 

## qip-NISQ
Comments:
- You could add somewhere an updated version of the nice graphic shown in your blog post. 
- Can also consider cross-citing the other notebooks related to this. 
- Please consider adding a markdown paragraph at the beginning with the explicit writing of the NISQ acronym. 
- Please consider adding also a link to Preskill's **Quantum** article on NISQ, citing it in that first paragraph, and putting it in a new markdown subsection just before the software versions section or at the end, similarly to [this](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/piqs-overview.ipynb#References) and other notebooks.
- This citation could be inside a new first paragraph that is a bit more general than the current one, giving a bit of context even independently on QuTiP implementations:
Something like: "This notebook illustrate how noise can be introduced in the simulation of a quantum circuit. Indeed, in real quantum devices, noise affects the perfect execution of gate-based quantum circuits, limiting their depths. This and other related notebooks show how it is possible to introduce different kinds of realistic noise in QuTiP quantum information processing module, and study their effects on desired protocols." 
- Can break the currently first paragraph in two (e.g., before "The simulator, under" with a double space), to enhance readability: short paragraphs are better than longer ones, especially in notebooks.
- I feel like the different kind of noises should be listed fairly at the beginning of the notebook, to better guide the reader on what to expect next. 
- hadwares: hardwares. 
- typo: "mothod": method
- typo: `Porcessor`: `Processor` (3 instances)
- Mention that hbar is one in the equation for H. 
-  "quantum device with  𝜎𝑧  and  𝜎𝑦  pulse.": pulses 
- "is one element longer the": longer than
- the attribute is `coeffs` not `coeff`
- that flip: that flips 
- equvilent: equivalent
- Controling single qubit: Controlling 
- Controling single qubit: Controlling a single qubit
- "some where else and is a distritization of a continuous function, you can also tell the processor two use them with cubic spline."---> "somewhere else and is a discretization of a continuous function, you can also tell the processor to use it with cubic spline."
- "and is valid even if the gate time is not much shorter than the decay time. ": if you have a citation to add here and put in the References section it would be great. 
- "have a drift": has a drift
- In the subtitles, consider adding "Decay time" before T1 and "Decoherence time" before T2. 
- "of the population at the excited state"--> "of the population of the excited state"( maybe?)
- "but don't want to run the simulation right now. You can extract":  right now, you
- return the noiseless part of the evolution elements. In contrast `get_noisy_qobjevo` return the noisy version: returns (twice)
- "containing noisy QobjEvo": "containing the "noisy" QobjEvo"
- Are block 21 and 22 correct? They seem empty and not useful 
- "the tlist, Type of the coefficients depend on the difinition of noise": this sentence sounds strange but I am not sure of the fix. Might be "the tlist. The type of".
- could print coeffs, tlist at the end (maybe). 
- gausian white noise: Gaussian
- Is "pulse noise" classical, in some sense? If yes, please point it out.

**Comment by nathanshammah** [comment]
## DJ algorithm (update)
Great updates on the review. Reads better and explains the results guiding more the reader. 
- One suggestion: 
- Update relevant sentence to this: "Different sub-classes of `Processor` find their pulses in different ways".
- "qip-circuitprocessor-DJ-algorithm": if CircuitProcessor is now Processor, maybe update name (or I might be confusing this) 

## qip-optpulseprocessor
- "is a the simulator": is a simulator 
- "equipted": equipped 
- "equipped with a method to find the pulse sequence for":"equipped with a method to find the **optimal** pulse sequence for", am I getting it right? This could be also the point to explain the meaning of `OptPulseProcessor` as an optimal pulse processor. 
-  "the method load_circuit": "the method `load_circuit`"
- and return: and returns
- hadamard: Hadamard 
- "Like the Processor, the simulation is calculated with the QuTiP solver": "the" assumes there is a given solver used, I would put "a". Or state that is mesolve as shown later. 
- the optmal control pulse: optimal
- toffoli: Toffoli
- "we can choose if we want to first to merge ": we can choose whether we want to first merge 
- "title="Contorl pulse ": "Control" (repeated)
- Please comment the end of notebook and the plots.

**Comment by nathanshammah** [comment]
By the way, for some reason these notebooks do not render at all in GitHub, if one clicks on "View". 

## spin-chain-model
- Please mention that you updated/modified the notebook at the beginning
- "In the new version of QuTiP,": "From QuTiP 4.5, "
- "to use the QuTiP solver": please specify what solver, or use "one of QuTiP solvers"
- "numerical `CircuitProcessor`": update to just `Processor` if it applies
- "Since the result of this this noise": this repeated
- "is still a pure state, we can visualize it on a Bloch sphere": add stop point.  
Maybe the command
`processor.add_noise(WhiteNoise(mean=0.1, std=0.2, dt=0.1))` is better added in block 37, before the plot, so that it is clear to the reader what noise block 37 is showing. 

Well done!

**Comment by BoxiLi** [comment]
Hi Nathan,  You mentioned that you were to looking into a “table of content” for the gates notebook. There is a jupyter notebook extension that can generate one automatically: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html BestBoxi   From: Nathan ShammahSent: Friday, September 27, 2019 3:55 AMTo: qutip/qutip-notebooksCc: Boxi Li; AuthorSubject: Re: [qutip/qutip-notebooks] Notebooks for GoSC NISQ simulator (#88) 1. All notebooksPlease add your name and possibly contact email to the top of notebooks.2. quantum-gatesCan add the fact that now gates can be applied in any position of the circuit.typo: "its the attributes"typo (?): "targets qubits"--> "target qubits"block 13 and 14: typo in comment "controlls", controlsblock 14: qutbi --> qubit(- This notebook is full of stuff, e.g., the list of gates, but someone might miss some important information as how to play with circuit properties, given later on. I am thinking of adding a table of contents with internal links to cells. It could be nice to have the latex version of gates for all of them. I will look into these enhancements myself.)## qip-NISQExcellent tutorial.Comments:Please consider adding a markdown paragraph at the beginning with the explicit writing of the NISQ acronym.Please consider adding also a link to Preskill's Quantum article, citing it in that first paragraph, and putting it in a new markdown subsection just before the software versions section or at the end, similarly to this and other notebooks.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nathanshammah** [comment]
In the `qip-NISQ.ipynb`, for clarity, you can move `Hadamard = hadamard_transform(1)` from block 9 and place it in block 12, as it is not used in the calculation before that.

**Comment by BoxiLi** [comment]
Hi Nathan, thanks for those comprehensive suggestions. It will still take some time for me to update the notebook.

As you suggested an explanation of "NISQ", I had a look at Preskill's article again. Then I realised that, according to his definition, NISQ simulator is actually a wrong name because NISQ refers to quantum computers of 50-100 qubits that are beyond the classical simulation but far from practical use like Shor's algorithm.

**Comment by ajgpitch** [comment]
> NISQ refers to quantum computers of 50-100 qubits that are beyond the classical simulation

Hmmm, maybe this is worth considering. Seems like the notebook name might be self-contradictory.

Personally I think NISQ is a bit of a buzz name and so should be avoided in titles and file names. I think we are better off just referring to noisy devices.

**Comment by ajgpitch** [comment]
I have merged qutip/qutip#1065

**Comment by nathanshammah** [comment]
I agree with you.

**Comment by BoxiLi** [comment]
> Can also consider cross-citing the other notebooks related to this.

Does anyone know how to do notebook cross-citing? I guess they don't have a permanent link before they are moved to nbviewer?

**Comment by BoxiLi** [comment]
Task list:
- [ ]  add an updated version of the graphic
- [ ] how to list the notebooks in the tutorials page
- [ ] Proof read

**Comment by ajgpitch** [comment]
I did some cross linking in
https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/optimal-control-overview.ipynb
seems I just used the nbviewer URL.

I would have thought relative paths should work, as they do for images, but
then I am not sure why I did not use them. Why not just give it a go.

**Comment by BoxiLi** [comment]
Thank you both for the advice. Both the absolute nbviewer URL and the relative path work. I hope the links will keep working when they are released.

**Comment by BoxiLi** [comment]
> By the way, for some reason these notebooks do not render at all in GitHub, if one clicks on "View".

I checked them after my update. GitHub can render them now, although I did nothing special and don't know why it failed to do it.

**Comment by BoxiLi** [comment]
@nathanshammah I have updated all the notebooks. 

As for how to list the notebooks in the tutorials page, I suggest that we put them under the qip section after the three existing notebooks with the order:

- introduction notebook
- optpulseprocessor
- DJ-algorithm

**Comment by nathanshammah** [comment]
> > By the way, for some reason these notebooks do not render at all in GitHub, if one clicks on "View".
> 
> I checked them after my update. GitHub can render them now, although I did nothing special and don't know why it failed to do it.

This was an instability that just recently received a patch by GitHub. https://twitter.com/natfriedman/status/1188941369114423296

**Comment by BoxiLi** [comment]
Thanks for the comment.

I added some links in the introduction notebook. Is it better to put it at the beginning (like this version) or at the end of the notebook?

After adding the links, I think on the tutorial page, spin chain model should be under the intro notebook:

- Quantum gates and circuits
- Toffoli gate to CNOT
- introduction notebook for the noisy simulator
- Spin chain qubit model
- optpulseprocessor
- DJ-algorithm

Regarding the reference, you mean like references on different noisy models or different simulator? Maybe it does worth some work on it.

**Comment by nathanshammah** [comment]
I agree with your proposal for the website, please go on if you can. All other changes are fine. Yes, I meant proper bibliographic references.

**Pull request merged**
