### PR TITLE
Updated notebook for tomography of an optical quantum state

### PR DESCRIPTION
**Pull request by quantshah**
I realised that I never got to adding the tomography section in the QuTiP tutorials page. I have updated the older merged notebook with some minor changes. Typos are fixed and I added some more explanations. In the end, I also added a discussion about noise. I recently implemented a quantum process tomography simulation too and will make a new PR to add that. With there two notebooks we can make a new section about tomography on the qutip tutorial page.

But first, I want to get this updated notebook merged and make a new section in the tutorials page about this.

@hodgestar @jakelishman @nathanshammah If you have some time, could you have a quick glance so that I can get this going?

### CODE REVIEW

**Comment by quantshah** [comment]
I removed the animated version of the reconstruction since they take time. We keep it simple with the refactored notebook.

**Comment by quantshah** [comment]
If you want to see the notebook then just click on the three dots next to the file in the "files changed" tab and click on "view file". Thanks

**Review by jakelishman — COMMENTED** [review]
Looks like a good notebook!  Some things I noticed:

- the file `.DS_Store` snuck into the index before your `.gitignore` changes - could you `gm rm .DS_Store` to get rid of it
- if you're changing the name of a notebook, can you make sure any links to it on the website and in the index notebook `index.ipynb` (in the root of this repo) are also updated?
- the first cell displays the final images in its output, but since there's no code in the cell, the images will disappear if someone tries to re-run the notebook.  Perhaps you could embed the images directly, rather than as a code output?  (I'm not entirely sure what's possible with Jupyter.)
- is there a way to restrict the output of the Hinton plots to only say, 15 of the Fock states, and/or only plot some of the labels?  The labels aren't legible, as things stand now.

**Comment by quantshah** [comment]
Thanks @jakelishman for the quick review. I took care of all your comments.

- The .DS_Store file is removed.
- I added a new section in the index for tomography
- The image is now embedded and called from the local images folder as the other notebooks
- I plot the restricted density matrix separately now which makes the indices clearer (but still a little overlap). I also explain what the Hinton plot is.

I added a section that considers reconstruction from data that has some noise added and added a bunch of references for faster maximum likelihood methods (MLE). I include also my own recent work on comparing MLE with neural-network based reconstruction. I need to polish the repo but the paper is out there with the basic code. All the code for this tutorial actually comes from the work in that paper. I will add some more notebooks to this tomography section showing slightly faster iMLE versions, how to tackle Gaussian noise and a process tomography example soon.

**Comment by quantshah** [comment]
@jakelishman any comments on this update?

**Review by jakelishman — APPROVED** [review]
There's one Hinton plot that's still illegible, but the others look much better now, and it's probably good that one of them shows the entire extent.

You probably want to PR to the website to add the tutorial to the index there, aswell.

**Comment by quantshah** [comment]
Thanks @jakelishman , the Hinton plot indices still are not perfect but I am okay with how it looks now. I will open a PR on the website to add the tutorial to the index there.

**Pull request merged**
