### PR TITLE
Organize QuTiP tutorials in a notebook index

### LINKED ISSUE #98: Number QuTiP tutorials
Momentarily it is difficult to follow the examples coherently because the order is alphabetical. Would it be possible to add numbers to all the examples?

### PR DESCRIPTION
**Pull request by IvanIsCoding**
Fixes #98

Adds a notebook index in the style of http://qutip.org/tutorials.html to organize the examples and make them easy to follow. The main Binder link also leads to the index after this change.

The issue asked for numbering to organize, but there was not a consensus on numbering as the best solution. Having an index is a solution in between because we keep the filenames as they are and add the order of the tutorial page.

### CODE REVIEW

**Comment by nathanshammah** [comment]
I like it. Would like more feedback from @ajgpitch @quantshah  or others. A possibile maintainance issue to me seems that people would add ipynb to the website but need also to update the index.ipynb file. How to remind them of that? Add something in the contribution guidelines? Do we have any for the notebooks?

**Comment by quantshah** [comment]
I agree with @nathanshammah on having a uniform minimal set of guidelines for writing notebooks (such as having qutip.about(), adding the index and documentation links on the website)

**Comment by nathanshammah** [comment]
Ok, so, the guidelines could go in another notebook or in readme named CONTRIBUTING.md. 

I am happy to merge this as is. I recently noticed this nice [index notebook in PoliAstro](https://mybinder.org/v2/gh/poliastro/poliastro/master?filepath=index.ipynb) (cc @astrojuanlu) and I propose two changes:
- (1) First, that the My Binder link behind the badge in the README in this repo and in qutip/qutip, points to the index notebook directly. 
- (2) Second, optionally, that images are added for each notebook. This is much longer to do and could be done in another PR. This may still be easier to implement than a complete Sphinx Gallery overhaul. I will open an Issue. 

Do you think you can address (1), @IvanIsCoding? It would help visitors not get lost when they open My Binder.

**Comment by IvanIsCoding** [comment]
I will add the CONTRIBUTING.md with the guidelines in this PR then. Also, this PR links the Binder badge in qutip-notebooks to the index.ipynb, so only a change in qutip/qutip is necessary.

**Comment by nathanshammah** [comment]
Wonderful, thanks @ivaniscoding.

**Pull request merged**
