### PR TITLE
notebooks for td_Qobj

### PR DESCRIPTION
**Pull request by Ericgig**
Development notebooks for the td_Qobj proposed in pull request #814 of qutip/qutip.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Just wondering why
```
str_QobjEvo(1, data=True)
```
returns
```
matrix of type '<class 'numpy.complex128'>
```
rather than a `fast_csr_matrix`
Just a question for my understanding.

**Comment by ajgpitch** [comment]
I have run the three notebooks. There use seems to be clear. The performance numbers seem very impressive.
@Ericgig I am happy for this to be merged

**Comment by Ericgig** [comment]
That is not normal.
`str_QobjEvo(1, data=True)` should return a `fast_csr_matrix`. (or qobj.data when/if other data format are made available).
If I run the notebook "development-qobjevo" as it is, I get a csr_matrix.
Could you tell me how you got it to return a matrix? Could it come from side effect of using different version of scipy?

**Comment by ajgpitch** [comment]
@Ericgig Was running first box in 'Other' section of 'development-qobjevo'

sorry it is type `fast_csr_matrix`
It's just the `repr` does not mention that - not your fault obviously.
```
<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 7 stored elements in Compressed Sparse Row format>
```
Could you run those 'Other' boxes, so the notebook has output for them please. 
Otherwise this is ready to merge. Go ahead when you are ready

**Pull request merged**
