### PR TITLE
Added notebooks for Permutational Invariant Q Solver

### PR DESCRIPTION
**Pull request by sahmed95**
The example notebooks for the Permutational Invariant Quantum Solver (dicke model). This works against the branch in PR : https://github.com/qutip/qutip/pull/753

Once the code is reviewed and merged. We can run the notebooks again with the latest master.
@ajgpitch 
@nathanshammah

### CODE REVIEW

**Comment by ajgpitch** [comment]
Thanks for the notebooks
I am ready to test again whenever. I had email conversation with @nathanshammah which suggested I should wait until another commit on qutip/qutip#753

**Comment by ajgpitch** [comment]
I have run these successfully. Technically and formatwise these look good. I am happy to merge them when qutip/qutip#753 is merged

**Comment by sahmed95** [comment]
Thanks for taking a look. We are working on the manuscript and hopefully by the end of the week it will be ready. Sorry for the slow response. Once the writing is done I will talk a final look and we can merge it. Some more tests can be added but in its current form the PR can be merged. The structure of the code will not change anyways.

**Comment by ajgpitch** [comment]
https://github.com/qutip/qutip/pull/753 now merged into master
I running the first of these against master - got an import error.
I assume there are few updates needed in these notebooks

**Comment by sahmed95** [comment]
Closed via #53

**Pull request closed without merging**
