### PR TITLE
Update for new stochastic version

### PR DESCRIPTION
**Pull request by Ericgig**
Updated the development notebooks concerning stochastic code to fit the version proposed in pull request #815 "stochastic" of qutip.

### CODE REVIEW

**Comment by ajgpitch** [comment]
I got the error below when running `smesolve-heterodyne`
@Ericgig any idea on this. I will pause testing for now.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-b14288492d5d> in <module>
      4                   dW_factors=[np.sqrt(2/gamma), np.sqrt(2/gamma)], m_ops=[[x, y]],
      5                   distribution='normal', store_measurement=True,
----> 6                   map_func=parallel_map)

~/GitHub/qutip/qutip/stochastic.py in smesolve(H, rho0, times, c_ops, sc_ops, e_ops, _safe_mode, args, **kwargs)
    571     sso = StochasticSolverOptions(True, H=H, state0=rho0, times=times,
    572                                   c_ops=c_ops, sc_ops=sc_ops, e_ops=e_ops,
--> 573                                   args=args, **kwargs)
    574 
    575     if _safe_mode:

TypeError: __init__() got an unexpected keyword argument 'd1'
```

**Comment by ajgpitch** [comment]
@Ericgig sorry, my fault, on wrong branch

**Comment by ajgpitch** [comment]
Please run version_table for development-smesolve-milstein-speed-test
Rename `development-smesolve-milstein` to `smesolve-milstein` and move to `../examples`

**Comment by ajgpitch** [comment]
Please run version_table for  development-smesolve-tests
Maybe use parallel_map in `development-smesolver-new-methods`. Took a long time to run boxes

**Comment by ajgpitch** [comment]
@Ericgig You'll see I have made a few small suggestions above.
I don't need to check this again, go ahead and merge when it's ready

**Comment by Ericgig** [comment]
development-smesolver-new-methods use only one trajectory and thus each run can't benefit from parallel_map. It is quite long but since you only have to run it once to convince yourself that the solvers work as intended. I have added some in `development-smesolve-tests` since it has some 5 min boxes that can benefit from it.

**Pull request merged**
