### PR TITLE
State-to-state transfer problem optimized by CRAB

### PR DESCRIPTION
**Pull request by JonathanUlm**
Example notebook showing a state-to-state transfer optimization using the CRAB algorithm.

### CODE REVIEW

**Comment by nonhermitian** [comment]
I think the last plot is missing from the notebook.  Other than that looks good.

**Comment by ajgpitch** [comment]
Yes, you need to add this line:
%matplotlib inline
before the imports in the first code box

**Comment by ajgpitch** [comment]
The description of the physics is very nice. I like the use of Latex for the vectors and Hamiltonian

**Comment by JonathanUlm** [comment]
Thanks for having a look at the notebook and thank you Alex for having the answer ready right away - it is now fixed.

**Pull request merged**
